"""Natural language → r7-cli command translation.

Uses OpenAI, Anthropic (Claude), or Google Gemini to convert a plain-English
request into the appropriate r7-cli command, then optionally executes it.

The system prompt is dynamically generated by introspecting the Click command
tree, so it always stays in sync with the actual CLI.
"""
from __future__ import annotations

import json
import subprocess
import sys
from typing import Any

import click
import httpx

from r7cli.config import Config
from r7cli.models import UserInputError


# ---------------------------------------------------------------------------
# Dynamic system prompt generation
# ---------------------------------------------------------------------------

_PROMPT_CACHE: str | None = None


def _build_system_prompt() -> str:
    """Walk the Click command tree and build a complete system prompt."""
    global _PROMPT_CACHE
    if _PROMPT_CACHE is not None:
        return _PROMPT_CACHE

    from r7cli.main import cli

    lines: list[str] = []
    lines.append(
        "You are an expert at the r7-cli command-line tool for the Rapid7 Command Platform.\n"
        "\n"
        "Given a user's natural language request, respond with ONLY the r7-cli command "
        "that accomplishes their goal. Do not include any explanation, markdown formatting, "
        "or backticks — just the raw command string.\n"
        "\n"
        "Below is the complete command reference generated from the CLI itself.\n"
    )

    # Global options
    lines.append("## Global Options (must appear BEFORE the solution/command name)\n")
    for param in cli.params:
        if isinstance(param, click.Option):
            opts = "/".join(param.opts)
            secondary = "/".join(param.secondary_opts) if param.secondary_opts else ""
            flag_str = f"{opts}" + (f" ({secondary})" if secondary else "")
            help_text = param.help or ""
            lines.append(f"  {flag_str} — {help_text}")
    lines.append("")

    # Walk command tree
    lines.append("## Commands\n")
    ctx = click.Context(cli, info_name="r7-cli", resilient_parsing=True)
    _walk_commands(cli, ctx, "r7-cli", lines, depth=0)

    lines.append("\n## Rules\n")
    lines.append("- Global flags go BEFORE the solution name: r7-cli -o table vm scans list")
    lines.append("- If the request is ambiguous, pick the most likely command.")
    lines.append("- For bulk data needs (>1000 items), prefer export commands over list commands.")
    lines.append("- If you truly cannot map the request to any r7-cli command, respond with:")
    lines.append("  ERROR: <brief explanation of why>")

    _PROMPT_CACHE = "\n".join(lines)
    return _PROMPT_CACHE


def _walk_commands(
    group: click.BaseCommand,
    parent_ctx: click.Context,
    prefix: str,
    lines: list[str],
    depth: int,
) -> None:
    """Recursively walk a Click command/group and append formatted lines."""
    if isinstance(group, click.MultiCommand):
        cmd_names = group.list_commands(parent_ctx)
        for name in cmd_names:
            # Skip the 'ai' command itself to avoid recursion in the prompt
            if name == "ai":
                continue
            cmd = group.get_command(parent_ctx, name)
            if cmd is None:
                continue
            full_name = f"{prefix} {name}"
            _format_command(cmd, full_name, lines, depth)
            if isinstance(cmd, click.MultiCommand):
                child_ctx = click.Context(cmd, parent=parent_ctx, info_name=name, resilient_parsing=True)
                _walk_commands(cmd, child_ctx, full_name, lines, depth + 1)


def _format_command(cmd: click.BaseCommand, full_name: str, lines: list[str], depth: int) -> None:
    """Format a single command with its options."""
    # Get the short help (first line of docstring)
    short_help = cmd.get_short_help_str(limit=80)
    indent = "  " * depth

    if isinstance(cmd, click.MultiCommand):
        lines.append(f"{indent}{full_name} — {short_help}")
    else:
        # Leaf command — include options
        opts_parts: list[str] = []
        if hasattr(cmd, "params"):
            for param in cmd.params:
                if isinstance(param, click.Option):
                    opt_str = "/".join(param.opts)
                    if param.is_flag:
                        opts_parts.append(f"[{opt_str}]")
                    elif param.type and hasattr(param.type, "name"):
                        opts_parts.append(f"[{opt_str} {param.type.name.upper()}]")
                    else:
                        opts_parts.append(f"[{opt_str} VALUE]")
                elif isinstance(param, click.Argument):
                    if param.required:
                        opts_parts.append(f"<{param.name}>")
                    else:
                        opts_parts.append(f"[{param.name}]")

        opts_str = " ".join(opts_parts) if opts_parts else ""
        lines.append(f"{indent}{full_name} {opts_str}".rstrip() + f" — {short_help}")


# ---------------------------------------------------------------------------
# Provider implementations
# ---------------------------------------------------------------------------

def _call_openai(api_key: str, user_message: str, timeout: int) -> str:
    """Call OpenAI Chat Completions API."""
    system_prompt = _build_system_prompt()
    resp = httpx.post(
        "https://api.openai.com/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": "gpt-4o-mini",
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message},
            ],
            "temperature": 0,
            "max_tokens": 300,
        },
        timeout=timeout,
    )
    resp.raise_for_status()
    data = resp.json()
    return data["choices"][0]["message"]["content"].strip()


def _call_claude(api_key: str, user_message: str, timeout: int) -> str:
    """Call Anthropic Messages API."""
    system_prompt = _build_system_prompt()
    resp = httpx.post(
        "https://api.anthropic.com/v1/messages",
        headers={
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "Content-Type": "application/json",
        },
        json={
            "model": "claude-sonnet-4-20250514",
            "max_tokens": 300,
            "system": system_prompt,
            "messages": [
                {"role": "user", "content": user_message},
            ],
            "temperature": 0,
        },
        timeout=timeout,
    )
    resp.raise_for_status()
    data = resp.json()
    content = data.get("content", [])
    if content and isinstance(content[0], dict):
        return content[0].get("text", "").strip()
    return ""


def _call_gemini(api_key: str, user_message: str, timeout: int) -> str:
    """Call Google Gemini API."""
    system_prompt = _build_system_prompt()
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={api_key}"
    resp = httpx.post(
        url,
        headers={"Content-Type": "application/json"},
        json={
            "system_instruction": {"parts": [{"text": system_prompt}]},
            "contents": [
                {"parts": [{"text": user_message}]},
            ],
            "generationConfig": {"temperature": 0, "maxOutputTokens": 300},
        },
        timeout=timeout,
    )
    resp.raise_for_status()
    data = resp.json()
    candidates = data.get("candidates", [])
    if candidates:
        parts = candidates[0].get("content", {}).get("parts", [])
        if parts:
            return parts[0].get("text", "").strip()
    return ""


_PROVIDERS = {
    "openai": _call_openai,
    "claude": _call_claude,
    "gemini": _call_gemini,
}


# ---------------------------------------------------------------------------
# Click command
# ---------------------------------------------------------------------------

@click.command("ai")
@click.argument("question", nargs=-1, required=True)
@click.option("-x", "--execute", is_flag=True, help="Execute the generated command immediately.")
@click.option("-y", "--yes", is_flag=True, help="Skip confirmation when using --execute.")
@click.option("--show-prompt", is_flag=True, hidden=True, help="Print the generated system prompt (debug).")
@click.pass_context
def ask_cmd(ctx, question, execute, yes, show_prompt):
    """Translate a natural language request into an r7-cli command.

    \b
    Requires an LLM provider to be configured via:
      --llm openai|claude|gemini  (global flag, before 'ai')
      --llm-key YOUR_KEY          (or use env vars below)

    \b
    Environment variables:
      R7_LLM_PROVIDER    — openai, claude, or gemini
      OPENAI_API_KEY     — for OpenAI
      ANTHROPIC_API_KEY  — for Claude
      GEMINI_API_KEY     — for Gemini
      R7_LLM_API_KEY     — generic fallback for any provider

    \b
    Examples:
      # Get the command for listing critical vulnerabilities
      r7-cli --llm openai ai show me critical vulnerabilities

    \b
      # Execute directly
      r7-cli --llm claude ai -x list all open investigations

    \b
      # Using env vars (no --llm flag needed if R7_LLM_PROVIDER is set)
      export R7_LLM_PROVIDER=gemini
      export GEMINI_API_KEY=your-key
      r7-cli ai how many assets do I have
    """
    config: Config = ctx.obj["config"]

    # Hidden debug flag to inspect the generated prompt
    if show_prompt:
        click.echo(_build_system_prompt())
        return

    if not config.llm_provider:
        click.echo(
            "Error: No LLM provider configured.\n\n"
            "Set one of:\n"
            "  --llm openai|claude|gemini  (global flag before 'ask')\n"
            "  R7_LLM_PROVIDER env var\n\n"
            "And provide the API key via --llm-key, or the provider's env var:\n"
            "  OPENAI_API_KEY, ANTHROPIC_API_KEY, or GEMINI_API_KEY",
            err=True,
        )
        sys.exit(1)

    if not config.llm_api_key:
        click.echo(
            f"Error: No API key for '{config.llm_provider}'.\n\n"
            f"Provide via --llm-key flag or set the appropriate env var:\n"
            f"  openai  → OPENAI_API_KEY\n"
            f"  claude  → ANTHROPIC_API_KEY\n"
            f"  gemini  → GEMINI_API_KEY\n"
            f"  (any)   → R7_LLM_API_KEY",
            err=True,
        )
        sys.exit(1)

    user_message = " ".join(question)
    provider_fn = _PROVIDERS[config.llm_provider]

    try:
        command = provider_fn(config.llm_api_key, user_message, config.timeout)
    except httpx.HTTPStatusError as exc:
        click.echo(f"LLM API error ({exc.response.status_code}): {exc.response.text[:200]}", err=True)
        sys.exit(2)
    except httpx.RequestError as exc:
        click.echo(f"Network error calling {config.llm_provider}: {exc}", err=True)
        sys.exit(3)

    # Check for error response from the LLM
    if command.startswith("ERROR:"):
        click.echo(command, err=True)
        sys.exit(1)

    # Strip any accidental markdown backticks
    command = command.strip("`").strip()
    if command.startswith("bash\n"):
        command = command[5:].strip()

    click.echo(f"  {command}")

    if execute:
        if not yes:
            confirm = click.confirm("Execute this command?", default=True)
            if not confirm:
                click.echo("Aborted.", err=True)
                return

        # Execute the command
        try:
            result = subprocess.run(
                command,
                shell=True,
                text=True,
            )
            sys.exit(result.returncode)
        except KeyboardInterrupt:
            click.echo("\nAborted.", err=True)
            sys.exit(130)
